branches:
  only:
  - v1

stages:
  - linter
  - test

dist: xenial

language: python

python:
  - 3.6
  - 3.7

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE=exodus.settings.dev

before_install:
  - sudo apt-get update
  - sudo apt-get install -y dexdump

install:
  - pip install -r requirements.txt

script:
  - cd exodus
  - python manage.py test

jobs:
  include:
    - name: "flake8 lint"
      stage: linter
      services: []
      before_install: []
      python: 3.7
      install:
        - pip install flake8
      script:
        - flake8 exodus/

    - name: "Dockerfile lint"
      stage: linter
      services: docker
      before_install: []
      install: []
      script:
        - docker run -i hadolint/hadolint:v1.19.0-45-gef91156-alpine < docker/Dockerfile

    - name: "Docker build test"
      stage: Test
      services: docker
      before_install: []
      install: []
      script:
        - docker build -t exodus . --file ./docker/Dockerfile
